SELECT ORDERDATE FROM ORDERS
UNION
SELECT SHIPTDATE FROM ORDERS
    WHERE SHIPDATE IS NOT NULL;

    EXTRACT(DAY FROM ORDERDATE) DAY,
    EXTRACT(MONTH FROM ORDERDATE) MONTH,
    EXTRACT(YEAR FROM ORDERDATE) YEAR,
    TO_NUMBER(TO_CHAR(ORDERDATE,'D')) WEEK_DAY,
    TO_NUMBER(TO_CHAR(ORDERDATE,'DDD')) YEAR_DAY,
    TO_CHAR(ORDERDATE,'DAY') DAY_NAME,
    TO_CHAR(ORDERDATE,'MONTH') MONTH_NAME,
    TO_NUMBER(TO_CHAR(ORDERDATE,'WW')) WEEK_NUMBER,
    TO_NUMBER(TO_CHAR(ORDERDATE,'Q')) QUARTER